[keys]
# ---MAINNET cartera real---
api_key_prod=
api_secret_prod=
url_base_api_prod=https://api.binance.com/api
url_base_api_1_prod=https://api1.binance.com
url_base_api_2_prod=https://api2.binance.com
url_base_api_3_prod=https://api3.binance.com
url_base_api_4_prod=https://api4.binance.com

# --- ENDPOINTS---
url_api_ping=/api/v3/ping
url_api_time=/api/v3/time
url_api_exchangeInfo=/api/v3/exchangeInfo
url_api_depth=/api/v3/depth
url_api_trades=/api/v3/trades
url_api_historicalTrades=/api/v3/historicalTrades
url_api_aggTrades=/api/v3/aggTrades
url_api_klines=/api/v3/klines
url_api_avgPrice=/api/v3/avgPrice
url_api_24hr=/api/v3/ticker/24hr
url_api_price=/api/v3/ticker/price
url_api_bookTicker=/api/v3/ticker/bookTicker
url_api_order=/api/v3/order
url_api_openOrders=/api/v3/openOrders
url_api_allOrders=/api/v3/allOrders
url_api_account=/api/v3/account
url_api_myTrades=/api/v3/myTrades
url_api_order_test=/api/v3/order/test

# --- WEBSOCKETS---
url_ws_stream_klines_prod=wss://stream.binance.com:9443/ws/symbol@kline_interval
url_ws_stream_trade_prod=wss://stream.binance.com:9443/ws/symbol@trade

# --- TESTNET cartera producción---
api_key_test=PONER AQUI API-KEY
api_secret_test=PONER AQUI API-SECRET
url_base_api_test=https://testnet.binance.vision
url_ws_stream_klines_test=wss://stream.testnet.binance.vision/ws/symbol@kline_interval
url_ws_stream_trade_test=wss://stream.testnet.binance.vision/ws/symbol@trade



